(defun t16-c8-convert ()
  (interactive)
  (let ((done nil) (count 0))
    (while (< count 100)
      (incf count)
      (skip-chars-forward "^\t\"")
      (cond ((= (char-after (point)) ?\")
	     (forward-char 1)
	     (skip-chars-forward "^\"")
	     (forward-char 1))
	    ((= (char-after (point)) ?\t)
	     (delete-char)
	     (insert ","))
	    (t (error 'invalid-state "program is broken!"))))))
